name: React Release

on:
  push:
    paths:
      - 'react/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pack
        run: |
          cd react
          apm pack
